# Site settings
title: Fabien Loup
description: >
  Hi, I am Fabien Loup. I'm a Software Developer and this is my blog.
baseurl: ""
url: "http://www.norydev.com"

# Build settings
markdown: kramdown
permalink: /writing/:title
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
sass:
  sass_dir: _sass
  style: compressed
